name: DockerTask_DebianInfo

on:
  push:
    branches: [main]
    
jobs:
  
  Run:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Make artifact dir
        shell: bash
        run: mkdir artifact
        
      - name: Build and run container
        shell: bash
        run: |
          docker build -t task .
          docker run --name TaskCont task
          
      - name: Getting info out of container and clear containers and images
        shell: bash
        run: |
          docker cp TaskCont:/task/info.txt ./artifact
          docker container prune
          docker image prune
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: info
          path: artifact
          
